version: '3'


services:

    kiwi_redis:
        image: redis:5
        restart: always
        volumes:
          - /docker_volumes/kiwi/redis:/data
        ports:
          - "3000:6379"

    kiwi-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        volumes:
          - static:/files/static:ro
          - socket:/files/socket
        ports:
          - "4000:80"

    kiwi-server:
        build:
          context: ./backend
          dockerfile: Dockerfile
        restart: always
        volumes:
          - socket:/socket
          - static:/src/server/static
        command: /src/init.sh

    kiwi-worker:
      build:
        context: ./backend
        dockerfile: Dockerfile
      restart: always
      command: python /src/background_worker.py


volumes:
    static:
    socket:
